import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from './dustline/node_modules/three/build/three.module.js';
import {DesertGame} from './dustline/lib/game';
import {MAP_SOLIDS,canOccupy} from './dustline/lib/world';
function harness(){const g:any=Object.create(DesertGame.prototype);Object.assign(g,{state:{phase:'playing',weapon:0,health:100,armor:100,dead:false,reloading:false,shots:0,hits:0,kills:0,headshots:0,deaths:0,feed:[]},inventory:[{ammo:30,reserve:90},{ammo:12,reserve:48}],position:new THREE.Vector3(0,0,23),velocity:new THREE.Vector3(),camera:new THREE.PerspectiveCamera(72,1,.06,120),scene:new THREE.Scene(),world:{targets:[],solids:MAP_SOLIDS},ray:new THREE.Raycaster(),bots:[],effects:[],decals:[],fireClock:0,switchClock:0,kick:0,burst:0,inspectClock:0,recoilPitch:0,recoilYaw:0,onGround:true,protection:0,feedID:0,shellGeometry:new THREE.CylinderGeometry(.01,.01,.04),shellMaterial:new THREE.MeshBasicMaterial(),decalGeometry:new THREE.CircleGeometry(.04),decalMaterial:new THREE.MeshBasicMaterial(),audio:{shot(){},impact(){},hurt(){},mechanical(){}},emit(){},tracer(){},impact(){},updateCamera(){}});g.camera.position.set(0,1.65,0);g.camera.updateMatrixWorld();return g}
test('map keeps spawn points and arch open, blocks walls, supports crouch clearance',()=>{assert.equal(canOccupy(0,23,0,1.8,MAP_SOLIDS),true);assert.equal(canOccupy(2.5,-18,0,1.8,MAP_SOLIDS),true);assert.equal(canOccupy(-7.5,-1,0,1.8,MAP_SOLIDS),false);assert.equal(canOccupy(5,13,0,1.8,MAP_SOLIDS),false);const overhang=[{x:0,z:0,w:3,d:3,h:1,y:1.2}];assert.equal(canOccupy(0,0,0,1.02,overhang),true);assert.equal(canOccupy(0,0,0,1.8,overhang),false)});
test('bot navigation reaches player through connected free cells',()=>{const g=harness();g.nav=new Uint8Array(49*65);for(let z=0;z<65;z++)for(let x=0;x<49;x++)g.nav[z*49+x]=canOccupy(x-24,z-32,0,1.8,MAP_SOLIDS,.43)?1:0;for(const [x,z] of [[1,-11],[11,2],[-1,5],[17,-24]]){const path=g.findPath(new THREE.Vector3(x,0,z),new THREE.Vector3(0,0,23));assert.ok(path.length>0,`route from ${x},${z}`);assert.ok(path.every((p:any)=>canOccupy(p.x,p.z,0,1.8,MAP_SOLIDS,.43)));assert.equal(path.at(-1).z,23)}});
test('reload conserves rounds, partial reserve works, and shooting is blocked during reload',()=>{const g=harness();g.inventory[0]={ammo:7,reserve:10};g.reload();assert.equal(g.state.reloading,true);g.shoot();assert.equal(g.inventory[0].ammo,7);g.updateReload(2.4);assert.equal(g.state.reloading,false);assert.deepEqual(g.inventory[0],{ammo:17,reserve:0});g.reload();assert.equal(g.state.reloading,false)});
test('raycast stops at cover; unobstructed head hit kills and consumes one round',()=>{const g=harness();const head=new THREE.Mesh(new THREE.SphereGeometry(.3),new THREE.MeshBasicMaterial());head.position.set(0,1.65,-10);head.userData={bot:0,part:'head'};const root=new THREE.Group();root.add(head);g.scene.add(root);const bot={hp:100,dead:0,root,light:{intensity:0},hitboxes:[head],name:'test'};g.bots=[bot];const wall=new THREE.Mesh(new THREE.BoxGeometry(5,5,1),new THREE.MeshBasicMaterial());wall.position.set(0,2,-5);g.scene.add(wall);g.world.targets=[wall];g.shoot();assert.equal(g.inventory[0].ammo,29);assert.equal(bot.hp,100);assert.equal(g.state.hits,0);g.world.targets=[];g.shoot();assert.equal(g.inventory[0].ammo,28);assert.equal(g.state.hits,1);assert.equal(g.state.kills,1);assert.equal(g.state.headshots,1);assert.equal(bot.hp,0)});
test('armor absorbs damage, spawn protection prevents it, and lethal damage causes one death',()=>{const g=harness();g.protection=1;g.damagePlayer(100,'enemy');assert.equal(g.state.health,100);g.protection=0;g.damagePlayer(10,'enemy');assert.equal(g.state.armor,96);assert.equal(g.state.health,94);g.damagePlayer(250,'enemy');assert.equal(g.state.dead,true);assert.equal(g.state.health,0);assert.equal(g.state.deaths,1);g.damagePlayer(10,'enemy');assert.equal(g.state.deaths,1)});
