#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
FPS_ARMS_ROOT="$ROOT_DIR/assets/third_party/fps_arms_ak74"
MODEL_ROOT="$FPS_ARMS_ROOT/Models/fps_ak-74m_animations"
TEXTURE_ROOT="$MODEL_ROOT/textures"
GODOT="$ROOT_DIR/engine/Godot.x86_64"
REV="c80a452e680c5a27c9e936176eb17e446869529a"
RAW="https://raw.githubusercontent.com/Ayush-Mohanty/FPS-Arms-3D/$REV"

mkdir -p "$TEXTURE_ROOT"
command -v curl >/dev/null || { echo "error: curl is required" >&2; exit 1; }

fetch() {
  local url="$1" dest="$2"
  mkdir -p "$(dirname "$dest")"
  echo "Downloading $(basename "$dest") ..."
  curl -fL --retry 3 --connect-timeout 20 "$url" -o "$dest"
}

# This Godot-ready scene contains the AK-74M, rigged first-person arms and the
# authored Draw / Idle / Walk / Run / Shot / Reload animation clips.
fetch "$RAW/Scenes_Scripts/sketchfab_scene_2.tscn" \
  "$FPS_ARMS_ROOT/FPS_AK74_Viewmodel.tscn"
fetch "$RAW/Models/fps_ak-74m_animations/license.txt" \
  "$MODEL_ROOT/license.txt"

for texture in \
  arms_baseColor.png \
  arms_metallicRoughness.png \
  arms_normal.png \
  ak74m_baseColor.png \
  ak74m_metallicRoughness.png \
  ak74m_normal.png; do
  fetch "$RAW/Models/fps_ak-74m_animations/textures/$texture" \
    "$TEXTURE_ROOT/$texture"
done

# The upstream scene uses its original repository's res://Models/... paths and
# resource UIDs generated by a different Godot project. Rewrite the path prefix
# and strip only ext_resource UIDs. Godot then resolves the copied textures by
# their valid local paths instead of warning about stale foreign UIDs.
python3 - "$FPS_ARMS_ROOT/FPS_AK74_Viewmodel.tscn" <<'PY'
from pathlib import Path
import re
import sys

path = Path(sys.argv[1])
text = path.read_text(encoding="utf-8")
text = text.replace(
    "res://Models/fps_ak-74m_animations/",
    "res://assets/third_party/fps_arms_ak74/Models/fps_ak-74m_animations/",
)
lines = []
for line in text.splitlines():
    if line.startswith("[ext_resource "):
        line = re.sub(r' uid="uid://[^"]+"', "", line)
    lines.append(line)
path.write_text("\n".join(lines) + "\n", encoding="utf-8")
PY

cat > "$FPS_ARMS_ROOT/ATTRIBUTION.txt" <<'EOF'
This work is based on "FPS AK-74m animations" (https://sketchfab.com/3d-models/fps-ak-74m-animations-94be8385c402474cacd39bc096c6ca14) by Cransh (https://sketchfab.com/ccransh) licensed under CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
EOF

if [[ -x "$GODOT" ]]; then
  echo
  echo "Importing FPS arms into Godot..."
  "$GODOT" --headless --path "$ROOT_DIR" --import
else
  echo
  echo "warning: bundled Godot editor not found at $GODOT"
  echo "Run: godot --headless --path '$ROOT_DIR' --import"
fi

echo
echo "Installed authored AK-74M first-person arms."
echo "Stale upstream texture UIDs were removed; local Godot paths are authoritative."
echo "Attribution was saved to: $FPS_ARMS_ROOT/ATTRIBUTION.txt"
echo "Run the source project with: ./engine/Godot.x86_64 --path ."
